### PR TITLE
feat: group ci and language versions

### PR DESCRIPTION
**Pull request by tagoro9**
**Description**

This PR groups CI related updates (github actions, pre commit and docker-compose) in a separate group and language versions in another group so it is easier to split runtime updates from build time / CI updates. To hopefully make it easiser to merge some of the PRs.

**Changes**

* feat: group ci and language versions

🚀 PR created with [fotingo](https://github.com/tagoro9/fotingo)

### CODE REVIEW

**Comment by tagoro9** [comment]
Ci is failing with a weird error - probably dependencies out of of date. Trying to fix

**Comment by OmarJaroudi** [comment]
I think the actual failure with commitlint requires you to just rebase onto main, but it also seems that we are still using node v16 in CI which doesn't seem right 🤔

**Comment by tagoro9** [comment]
Removed the dependency on node!

**Comment by tagoro9** [comment]
CI is missing the lint release notes still

**Review by Toolo — APPROVED** [review]

**Pull request merged**
